server:
  port: 8761

eureka:
  instance:
    hostname: registration-service
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://user:123456@registration-service:8761/eureka/