sudo:
  required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=wagzel/microservices-config
  - docker build -t $CONFIG:$COMMIT ./configuration-service
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=wagzel/microservices-registration-service
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=wagzel/microservices-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway-service
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # AUTH SERVICE
  - export AUTH_SERVICE=wagzel/microservices-auth
  - docker build -t $AUTH_SERVICE:$COMMIT ./authorization-service
  - docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
  - docker push $AUTH_SERVICE

  # HELLO SERVICE
  - export $HELLO_SERVICE=wagzel/microservices-hello
  - docker build -t $HELLO_SERVICE:$COMMIT ./hello-service
  - docker tag $HELLO_SERVICE:$COMMIT $HELLO_SERVICE:$TAG
  - docker push $HELLO_SERVICE

notifications:
  email:
    - wag6051@gmail.com