sudo:
  required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login-u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=wagzel/microservices-config
  - docker build -t $CONFIG_$COMMIT ./configuration-service
  - docker tag $CONFIG_$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=wagzel/microservices-registration-service
  - docker build -t $REGISTRY_$COMMIT ./registration-service
  - docker tag $REGISTRY_$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=wagzel/microservices-gateway
  - docker build -t $GATEWAY_$COMMIT ./gateway-service
  - docker tag $GATEWAY_$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # AUTH SERVICE
  - export AUTH_SERVICE=wagzel/microservices-auth
  - docker build -t $AUTH_SERVICE_$COMMIT ./authorization-service
  - docker tag $AUTH_SERVICE_$COMMIT $AUTH_SERVICE:$TAG
  - docker push $AUTH_SERVICE

  # HELLO SERVICE
  - export $HELLO_SERVICE=wagzel/microservices-hello
  - docker build -t $HELLO_SERVICE_$COMMIT ./hello-service
  - docker tag $HELLO_SERVICE_$COMMIT $HELLO_SERVICE_$TAG
  - docker push $HELLO_SERVICE

notifications:
  email:
    - wag6051@gmail.com