server:
  port: 1000

eureka:
  instance:
    hostname: registration-service
    prefer-ip-address: true
    metadata-map:
      user.name: user
      user.password: 123456
  client:
    service-url:
      defaultZone: http://user:123456@registration-service:8761/eureka/

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native