logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

eureka:
  instance:
    hostname: registration-service
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://user:123456@registration-service:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://authorization-service:1001/uaa/users/current